# Generated by Django 4.1.1 on 2022-10-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='NIP',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='tanggal_lahir',
            field=models.DateField(max_length=50),
        ),
    ]
