# Generated by Django 4.1.1 on 2022-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0003_alter_dosen_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIP', models.IntegerField(null=True)),
                ('nama', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('alamat_rumah', models.CharField(max_length=50)),
            ],
        ),
    ]
