# Generated by Django 4.1.1 on 2022-10-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0007_dosen_mahasiswa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='NIP',
            field=models.IntegerField(max_length=50),
        ),
    ]
