# Generated by Django 4.1.1 on 2022-10-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0008_alter_dosen_nip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='NIP',
        ),
    ]
