# Generated by Django 4.1.1 on 2022-10-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0012_remove_dosen_alamat_rumah_remove_dosen_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='alamat_rumah',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='fakultas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='prodi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='tanggal_lahir',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
