# Generated by Django 4.1.1 on 2022-10-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0013_dosen_alamat_rumah_dosen_email_dosen_fakultas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='alamat_rumah',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='fakultas',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='tanggal_lahir',
        ),
    ]
