# Generated by Django 4.1.1 on 2022-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0014_remove_dosen_alamat_rumah_remove_dosen_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
