# Generated by Django 4.1.1 on 2022-10-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0016_dosen_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
