# Generated by Django 4.1.1 on 2022-10-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0018_dosen_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='fakultas',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
