# Generated by Django 4.1.1 on 2022-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0020_dosen_prodi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='alamat_rumah',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
