# Generated by Django 4.1.1 on 2022-10-05 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0021_dosen_alamat_rumah'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='tendik_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faperta.tendik'),
        ),
    ]
